### ISSUE TITLE
No datapoints found

### ISSUE THREAD

**Issue by nykraj** [rbaumgar/monitor-demo-app#1]
Hi, 
Have followed all the steps and when I am running the below query in PromQL interface getting no datapoints found
<img width="1041" alt="Screenshot 2020-05-30 at 11 08 35 AM" src="https://user-images.githubusercontent.com/23098297/83320523-099efe00-a266-11ea-8d49-872cbffc41b5.png">

OpenShift 4.3

**Comment by rbaumgar** [comment]
It looks like you are looking at the system Prometheus UI. Look at the project based metric. Therefor you have to switch to developer mode.

**Comment by rbaumgar** [comment]
no update
